apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: {{ .Values.app.name }}
  name: {{ .Values.app.name }}
spec:
  selector:
    matchLabels:
      app: {{ .Values.app.name }}
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: {{ .Values.app.name }}
    spec:
      containers:
        - name: {{ .Values.app.name }}
          image: {{ .Values.image.name }}
          args:
            - --bitcoin.{{ .Values.app.network }}
            - --bitcoind.zmqpubrawblock=tcp://{{ .Values.app.btcRpcHostName }}:28332
            - --bitcoind.zmqpubrawtx=tcp://{{ .Values.app.btcRpcHostName }}:28333
            - --bitcoind.rpchost={{ .Values.app.btcRpcHostName }}:8332
            - --externalip={{ .Values.app.externalIP }}
            - --tlsextradomain={{ .Values.app.name }}-service
            - --wallet-unlock-password-file=/tmp/pass/wallet
            {{- range .Values.args }}
            - {{.}}
            {{- end }}
          resources:
            requests:
              cpu: {{ .Values.resources.requests.cpu }}
              memory: {{ .Values.resources.requests.memory }}
            limits:
              cpu: {{ .Values.resources.limits.cpu }}
              memory: {{ .Values.resources.limits.memory }}
          ports:
            - containerPort: {{ .Values.service.port }}
            - containerPort: {{ .Values.service.rpcPort }}
            - containerPort: {{ .Values.service.connectPort }}
          volumeMounts:
            - mountPath: /root/.lnd
              name: storage
            - mountPath: /tmp/pass
              name: lnpw
              readOnly: true
      volumes:
        - name: storage
          persistentVolumeClaim:
            claimName: {{ .Values.app.name }}-pvc
        - name: lnpw
          secret:
            secretName: {{ .Values.credential.lnpwSecretName }}
            items:
            - key: WALLET_PASS
              path: wallet