apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ .Values.app.name }}
  name: {{ .Values.app.name }}-external-service
spec:
  selector:
    app: {{ .Values.app.name }}
  ports:
  - name: connect
    port: {{ .Values.service.connectPort }}
    targetPort: {{ .Values.service.connectTargetPort }}
    protocol: TCP
  type: LoadBalancer
