apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: {{ .Values.app.name }}
  name: {{ .Values.app.name }}
spec:
  selector:
    matchLabels:
      app: {{ .Values.app.name }}
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: {{ .Values.app.name }}
    spec:
      containers:
        - name: {{ .Values.app.name }}
          image: {{ .Values.image.name }}
          args:
            - -printtoconsole
            - -dbcache=500
            - -maxconnections=60
            - -maxuploadtarget=1000
            - -blocksonly
            - -disablewallet
          resources:
            requests:
              cpu: {{ .Values.resources.requests.cpu }}
              memory: {{ .Values.resources.requests.memory }}
            limits:
              cpu: {{ .Values.resources.limits.cpu }}
              memory: {{ .Values.resources.limits.memory }}
          env: 
            - name: BITCOIN_DATA
              value: /bitcoin/.bitcoin
          ports:
            - containerPort: {{ .Values.service.port }}
            - containerPort: {{ .Values.service.rpcPort }}
          volumeMounts:
            - mountPath: /bitcoin/.bitcoin
              name: storage
      volumes:
        - name: storage
          persistentVolumeClaim:
            claimName: {{ .Values.app.name }}-pvc
