apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: {{ .Values.app.name }}
  name: {{ .Values.app.name }}
spec:
  selector:
    matchLabels:
      app: {{ .Values.app.name }}
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: {{ .Values.app.name }}
    spec:
      containers:
        - name: {{ .Values.app.name }}
          image: {{ .Values.image.name }}
          resources:
            requests:
              cpu: {{ .Values.resources.requests.cpu }}
              memory: {{ .Values.resources.requests.memory }}
            limits:
              cpu: {{ .Values.resources.limits.cpu }}
              memory: {{ .Values.resources.limits.memory }}
          ports:
            - containerPort: {{ .Values.service.port }}
            - containerPort: {{ .Values.service.rpcPort }}
          volumeMounts:
            - mountPath: /bitcoin/.bitcoin
              name: storage
            - mountPath: /bitcoin/.bitcoin/bitcoin.conf
              subPath: bitcoin.conf
              name: bitcoin-config
      volumes:
        - name: storage
          persistentVolumeClaim:
            claimName: {{ .Values.app.name }}-pvc
        - name: bitcoin-config
          configMap:
            name: {{ .Values.config.btcConfigMap }}
            items:
              - key: bitcoin.conf  
                path: bitcoin.conf 
