apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: {{ .Values.app.name }}
  name: {{ .Values.app.name }}
spec:
  selector:
    matchLabels:
      app: {{ .Values.app.name }}
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: {{ .Values.app.name }}
    spec:
      containers:
        - name: {{ .Values.app.name }}
          image: {{ .Values.image.name }}
          env: 
            - name: RPCUSER
              valueFrom:
                configMapKeyRef:
                  key: {{ .Values.config.rpcUser }}
                  name: {{ .Values.config.btcConfigMap }}
            - name: QDB_PG_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: QDB_PG_PASSWORD
                  name: bitraw-questdb-db-secrets
          ports:
            - containerPort: {{ .Values.service.port }}
          volumeMounts:
            - mountPath: /bitcoin/.bitcoin
              name: storage
            initialDelaySeconds: 180
            periodSeconds: 60
            timeoutSeconds: 30
      volumes:
        - name: storage
          persistentVolumeClaim:
            claimName: {{ .Values.app.name }}-pvc
