apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: {{ .Values.app.name }}
  name: {{ .Values.app.name }}
spec:
  selector:
    matchLabels:
      app: {{ .Values.app.name }}
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: {{ .Values.app.name }}
    spec:
      containers:
        - name: {{ .Values.app.name }}
          image: {{ .Values.image.name }}
          args:
            - {{ .Values.bitcoin.net }}
            - -dbchache={{ .Values.bitcoin.dbcache }}
            - {{ .Values.bitcoin.prune }}
            {{- range .Values.args }}
            - {{.}}
            {{- end }}
                       # - -rpcauth=commodity_manager:ce2f62c4d5caeb71fac604efa4fcc472$ae97fbf4b95e93522414bab58b1b61c811675f10c9ee1b58b8f3b36fecaabc2b
          resources:
            requests:
              cpu: {{ .Values.resources.requests.cpu }}
              memory: {{ .Values.resources.requests.memory }}
            limits:
              cpu: {{ .Values.resources.limits.cpu }}
              memory: {{ .Values.resources.limits.memory }}
          env: 
            - name: BITCOIN_DATA
              value: /bitcoin/.bitcoin
          ports:
            - containerPort: {{ .Values.service.port }}
            - containerPort: {{ .Values.service.rpcPort }}
            - containerPort: {{ .Values.service.zmqBlockPort }}
            - containerPort: {{ .Values.service.zmqTxPort }}
          volumeMounts:
            - mountPath: /bitcoin/.bitcoin
              name: storage
      volumes:
        - name: storage
          persistentVolumeClaim:
            claimName: {{ .Values.app.name }}-pvc
