apiVersion: v1
kind: Service
metadata:  
  labels:
    app: {{ .Values.app.name }}
  name: {{ .Values.app.name }}-service
spec:
  selector:    
    app: {{ .Values.app.name }}
  type: ClusterIP
  ports:  
  - name: http
    port: {{ .Values.service.port }}
    targetPort: {{ .Values.service.targetPort }}
    protocol: TCP
  - name: http
    port: {{ .Values.service.rpcPort }}
    targetPort: {{ .Values.service.rpcTargetPort }}
    protocol: TCP
