apiVersion: v1
kind: Service
metadata:  
  labels:
    app: {{ .Values.app.name }}
  name: {{ .Values.app.name }}-service
spec:
  selector:    
    app: {{ .Values.app.name }}
  type: {{ .Values.service.type }}
  ports:  
  - name: http
    port: {{ .Values.service.port }}
    targetPort: {{ .Values.service.targetPort }}
    protocol: TCP
  - name: rpc
    port: {{ .Values.service.rpcPort }}
    targetPort: {{ .Values.service.rpcTargetPort }}
    protocol: TCP  
  - name: zmqTx
    port: {{ .Values.service.zmqTxPort }}
    targetPort: {{ .Values.service.zmqTxTargetPort }}
    protocol: TCP
  - name: zmqBlock
    port: {{ .Values.service.zmqBlockPort }}
    targetPort: {{ .Values.service.zmqBlockTargetPort }}
    protocol: TCP
