
app:
  name: bitraw-bots

image:
  name: lackrobin/bitraw-bots:latest
  pullPolicy: IfNotPresent

config:
  configMapName: bitraw-bot-conf
  secretName: bitraw-bot-secret
  kcClientSecretName: bitraw-bot-kc-client-secret
  userNameField: KC_USER1_NAME
  userName: nobody@devnull.com
  userPasswordField: KC_USER1_PASSWORD
  user2NameField: KC_USER2_NAME
  user2Name: void@devnull.com
  user2PasswordField: KC_USER2_PASSWORD  
  grpcHostnameField: GRPC_SERVER
  grpcHostname: dingir-matchengine:50051
  kcClientNameField: KC_CLIENT_ID
  kcClientName: typescript-testsuite
  kcClientSecretField: KC_CLIENT_SECRET

resources: {}
  # limits:
  #  cpu: 100m
  #  memory: 128Mi
  # requests:
  #  cpu: 100m
  #  memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}
