apiVersion: v1
kind: ConfigMap
metadata:
 name:  {{ .Values.config.configMapName }}
 namespace: default
data:
 {{ .Values.config.userNameField }}: {{ .Values.config.userName }}
 {{ .Values.config.user2NameField }}: {{ .Values.config.user2Name }}
 {{ .Values.config.grpcHostnameField }}: {{ .Values.config.grpcHostname }}