apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: {{ .Values.app.name }}
  name: {{ .Values.app.name }}
spec:
  selector:
    matchLabels:
      app: {{ .Values.app.name }}
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: {{ .Values.app.name }}
    spec:
      containers:
        - name: {{ .Values.app.name }}
          image: {{ .Values.image.name }}
          env: 
            - name: KC_USER1_NAME
              valueFrom:
                configMapKeyRef:
                  key: {{ .Values.config.userNameField }}
                  name: {{ .Values.config.configMapName }}
            - name: KC_USER1_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: {{ .Values.config.userPasswordField }}
                  name: bitraw-bot-secret
            - name: KC_USER2_NAME
              valueFrom:
                configMapKeyRef:
                  key: {{ .Values.config.user2NameField }}
                  name: {{ .Values.config.configMapName }}
            - name: KC_USER2_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: {{ .Values.config.user2PasswordField }}
                  name: bitraw-bot-secret