
app:
  name: bitcoind

image:
  name: ruimarinho/bitcoin-core
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 8333
  targetPort: 8333
  rpcPort: 8332
  rpcTargetPort: 8332
  zmqPort: 28333
  zmqTargetPort: 28333
  

ingress:
  host: btc.bitraw.io

storage:
  size: 500Gi

resources:
  requests:
    cpu: 200m
    memory: 1Gi
  limits:
    cpu: 500m
    memory: 2Gi

args:
  - -printtoconsole
  - -dbcache=500
  - -maxconnections=60
  - -maxuploadtarget=1000
  - -blocksonly
  - -disablewallet
  - -server
  - -listen
  - -rpcbind=0.0.0.0
  - -rpcallowip=0.0.0.0/0
  - -rpcuser=test
  - -rpcpassword=test
  - -zmqpubhashblock="tcp://[::1]:28333"

nodeSelector: {}

tolerations: []

affinity: {}
