
app:
  name: bitcoind

image:
  name: ruimarinho/bitcoin-core
  pullPolicy: IfNotPresent

service:
  type: LoadBalancer
  port: 8333
  targetPort: 8333
  rpcPort: 8332
  rpcTargetPort: 8332
  

ingress:
  host: btc.bitraw.io

storage:
  size: 500Gi

config:
  btcConfigMap: bitcoin-default-conf

resources:
  requests:
    cpu: 200m
    memory: 1Gi
  limits:
    cpu: 500m
    memory: 2Gi

# arguments:
# - blocksonly

nodeSelector: {}

tolerations: []

affinity: {}
